version: '3'
services:
  backend-gyant:
    container_name: backend-gyant
    #    build: .
    image: node:16.18.1
    working_dir: /app
    command: npm run start:debug
    environment:
      - PORT=3000
      - JWT_SECRET=foo
      - JWT_TTL=3600s
      - IGNORE_TTL=1
    ports:
      - "8080:3000"
      - "9229:9229"
    volumes:
      - ".:/app"
    depends_on:
      - database-gyant
      - cache-gyant
  database-gyant:
    container_name: database-gyant
    image: mongo:6.0.3
    ports:
      - 27017:27017
    volumes:
      - gyant_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=gyant
  cache-gyant:
    container_name: cache-gyant
    image: redis:alpine
    ports:
      - 6379:6379
volumes:
  gyant_data: {}