version: '3'
services:
  backend-gyant:
    container_name: backend-gyant
    build: .
    command: sh -c "npm install --ci && npm run start:debug"
    user: node
    environment:
      - PORT=3000
      - JWT_SECRET=foo
      - JWT_TTL=3600s
      - IGNORE_TTL=1
    ports:
      - "8080:3000"
      - "9229:9229"
    volumes:
      - ".:/app"
    depends_on:
      - database-gyant
  database-gyant:
    container_name: database-gyant
    image: mongo:6.0.3
    ports:
      - 27017:27017
    volumes:
      - ./data/dump/gyant:/dump/
      - gyant_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=gyant
volumes:
  gyant_data: {}